name: Supabase Webhook

on:
  repository_dispatch:
    types: [pirep_insert, atc_insert]

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Run webhook script
        run: |
          node script.js
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
